"""Card tool specs."""

from __future__ import annotations

from kaiten_cli.models import ExampleSpec, OperationSpec, ResponsePolicy, RuntimeBehavior
from kaiten_cli.registry.base import make_tool
from kaiten_cli.runtime_behaviors import archive_card_request, execute_cards_list_all
from kaiten_cli.transforms import DEFAULT_LIMIT


LIST_CARD_SCHEMA = {
    "type": "object",
    "properties": {
        "query": {"type": "string", "description": "Full-text search query"},
        "space_id": {"type": "integer", "description": "Filter by space ID"},
        "board_id": {"type": "integer", "description": "Filter by board ID"},
        "column_id": {"type": "integer", "description": "Filter by column ID"},
        "lane_id": {"type": "integer", "description": "Filter by lane ID"},
        "condition": {"type": "integer", "enum": [1, 2], "description": "1=active, 2=archived"},
        "type_id": {"type": "integer", "description": "Filter by card type ID"},
        "owner_id": {"type": "integer", "description": "Filter by owner user ID"},
        "responsible_id": {"type": "integer", "description": "Filter by responsible user ID"},
        "tag_ids": {"type": "string", "description": "Comma-separated tag IDs"},
        "member_ids": {"type": "string", "description": "Comma-separated member IDs"},
        "states": {"type": "string", "description": "Comma-separated states (1=queued,2=inProgress,3=done)"},
        "created_after": {"type": "string", "description": "ISO datetime filter"},
        "created_before": {"type": "string", "description": "ISO datetime filter"},
        "updated_after": {"type": "string", "description": "ISO datetime filter"},
        "updated_before": {"type": "string", "description": "ISO datetime filter"},
        "due_date_after": {"type": "string", "description": "ISO datetime filter"},
        "due_date_before": {"type": "string", "description": "ISO datetime filter"},
        "external_id": {"type": "string", "description": "External ID filter"},
        "overdue": {"type": "boolean", "description": "Filter overdue cards"},
        "asap": {"type": "boolean", "description": "Filter ASAP cards"},
        "archived": {"type": "boolean", "description": "Include archived"},
        "limit": {"type": "integer", "description": "Max results (default 50, max 100)"},
        "offset": {"type": "integer", "description": "Pagination offset"},
        "compact": {
            "type": "boolean",
            "description": "Return compact response without heavy fields (avatars, nested user objects)",
            "default": False,
        },
        "relations": {
            "type": "string",
            "description": "Comma-separated relations to include (members,type,custom_properties,...) or 'none' to exclude all. Default: include all.",
        },
        "fields": {
            "type": "string",
            "description": "Comma-separated field names to return per card. Strips everything else. Example: 'id,title,created,last_moved_to_done_at'",
        },
    },
}


TOOLS = (
    make_tool(
        canonical_name="cards.list",
        mcp_alias="kaiten_list_cards",
        description="Search and list Kaiten cards with filtering. Conditions: 1=active, 2=archived. States: 1=queued, 2=inProgress, 3=done.",
        input_schema=LIST_CARD_SCHEMA,
        operation=OperationSpec(
            method="GET",
            path_template="/cards",
            query_fields=(
                "query",
                "space_id",
                "board_id",
                "column_id",
                "lane_id",
                "condition",
                "type_id",
                "owner_id",
                "responsible_id",
                "tag_ids",
                "member_ids",
                "states",
                "created_after",
                "created_before",
                "updated_after",
                "updated_before",
                "due_date_after",
                "due_date_before",
                "external_id",
                "overdue",
                "asap",
                "archived",
                "limit",
                "offset",
                "relations",
            ),
        ),
        response_policy=ResponsePolicy(compact_supported=True, fields_supported=True, default_limit=DEFAULT_LIMIT, result_kind="list"),
        examples=(
            ExampleSpec(command="kaiten cards list --board-id 10 --limit 5 --compact --json", description="List cards on a board."),
            ExampleSpec(command='kaiten cards list --query "bug" --fields id,title,state', description="Search cards by query."),
        ),
    ),
    make_tool(
        canonical_name="cards.get",
        mcp_alias="kaiten_get_card",
        description="Get a Kaiten card by ID. Supports numeric ID or card key (e.g. PROJ-123).",
        input_schema={
            "type": "object",
            "properties": {
                "card_id": {"type": ["integer", "string"], "description": "Card ID or key (e.g. PROJ-123)"},
                "compact": {
                    "type": "boolean",
                    "description": "Return compact response without heavy fields (avatars, nested user objects)",
                    "default": False,
                },
                "fields": {
                    "type": "string",
                    "description": "Comma-separated field names to keep in the response. Example: 'id,title,state'",
                },
            },
            "required": ["card_id"],
        },
        operation=OperationSpec(method="GET", path_template="/cards/{card_id}", path_fields=("card_id",)),
        response_policy=ResponsePolicy(compact_supported=True, fields_supported=True, result_kind="entity"),
        examples=(
            ExampleSpec(command="kaiten cards get --card-id 123", description="Get a card by numeric ID."),
            ExampleSpec(command="kaiten cards get --card-id 123 --compact --fields id,title,state --json", description="Get a narrow card response."),
        ),
    ),
    make_tool(
        canonical_name="cards.create",
        mcp_alias="kaiten_create_card",
        description="Create a new Kaiten card. Title max 1024 chars, description max 32768 chars.",
        input_schema={
            "type": "object",
            "properties": {
                "title": {"type": "string", "description": "Card title (1-1024 chars)"},
                "board_id": {"type": "integer", "description": "Target board ID"},
                "compact": {
                    "type": "boolean",
                    "description": "Return compact response without heavy fields (avatars, nested user objects)",
                    "default": False,
                },
                "fields": {
                    "type": "string",
                    "description": "Comma-separated field names to keep in the response. Example: 'id,title,state'",
                },
                "column_id": {"type": "integer", "description": "Target column ID"},
                "lane_id": {"type": "integer", "description": "Target lane ID"},
                "description": {"type": "string", "description": "Card description (max 32768)"},
                "due_date": {"type": ["string", "null"], "description": "Deadline (ISO 8601)"},
                "asap": {"type": "boolean", "description": "ASAP marker"},
                "size_text": {"type": "string", "description": "Size (e.g. S, M, L, 1, 23.45)"},
                "owner_id": {"type": "integer", "description": "Owner user ID"},
                "type_id": {"type": "integer", "description": "Card type ID"},
                "external_id": {"type": "string", "description": "External ID (max 1024)"},
                "sort_order": {"type": "number", "description": "Position in cell"},
                "position": {"type": "integer", "enum": [1, 2], "description": "1=first, 2=last in cell"},
                "properties": {"type": "object", "description": "Custom properties as {id_N: value}"},
                "tags": {"type": "array", "items": {"type": "string"}, "description": "Tags to attach"},
                "sprint_id": {"type": "integer", "description": "Sprint ID to assign card to"},
                "planned_start": {"type": ["string", "null"], "description": "Planned start date (ISO 8601)"},
                "planned_end": {"type": ["string", "null"], "description": "Planned end date (ISO 8601)"},
                "responsible_id": {"type": "integer", "description": "Responsible user ID"},
                "condition": {"type": "integer", "enum": [1, 2], "description": "1=active, 2=archived"},
                "due_date_time_present": {"type": "boolean", "description": "True if due_date includes time component"},
                "expires_later": {"type": "boolean", "description": "Expires later flag"},
                "estimate_workload": {"type": "integer", "description": "Estimated workload in minutes (resource planning)"},
                "child_card_ids": {"type": "array", "items": {"type": "integer"}, "description": "Child card IDs to link (max 1)"},
                "parent_card_ids": {"type": "array", "items": {"type": "integer"}, "description": "Parent card IDs to link (max 1)"},
                "project_id": {"type": "string", "description": "Project UUID to attach card to"},
            },
            "required": ["title", "board_id"],
        },
        operation=OperationSpec(
            method="POST",
            path_template="/cards",
            body_fields=(
                "title",
                "board_id",
                "column_id",
                "lane_id",
                "description",
                "due_date",
                "asap",
                "size_text",
                "owner_id",
                "type_id",
                "external_id",
                "sort_order",
                "position",
                "properties",
                "tags",
                "sprint_id",
                "planned_start",
                "planned_end",
                "responsible_id",
                "condition",
                "due_date_time_present",
                "expires_later",
                "estimate_workload",
                "child_card_ids",
                "parent_card_ids",
                "project_id",
            ),
        ),
        response_policy=ResponsePolicy(compact_supported=True, fields_supported=True, result_kind="entity"),
        examples=(
            ExampleSpec(command='kaiten cards create --title "Smoke task" --board-id 10 --json', description="Create a card."),
            ExampleSpec(command='kaiten cards create --title "Smoke task" --board-id 10 --compact --fields id,title,state --json', description="Create a card with a narrow response."),
        ),
    ),
    make_tool(
        canonical_name="cards.update",
        mcp_alias="kaiten_update_card",
        description="Update a Kaiten card. Use condition=2 to archive, set column_id/board_id to move.",
        input_schema={
            "type": "object",
            "properties": {
                "card_id": {"type": ["integer", "string"], "description": "Card ID or key"},
                "compact": {
                    "type": "boolean",
                    "description": "Return compact response without heavy fields (avatars, nested user objects)",
                    "default": False,
                },
                "fields": {
                    "type": "string",
                    "description": "Comma-separated field names to keep in the response. Example: 'id,title,state'",
                },
                "title": {"type": "string", "description": "New title"},
                "description": {"type": ["string", "null"], "description": "New description"},
                "board_id": {"type": "integer", "description": "Move to board"},
                "column_id": {"type": "integer", "description": "Move to column"},
                "lane_id": {"type": "integer", "description": "Move to lane"},
                "sort_order": {"type": "number", "description": "Position in cell"},
                "owner_id": {"type": "integer", "description": "New owner user ID"},
                "type_id": {"type": "integer", "description": "Card type ID"},
                "condition": {"type": "integer", "enum": [1, 2], "description": "1=active, 2=archived"},
                "due_date": {"type": ["string", "null"], "description": "Deadline (ISO 8601 or null)"},
                "asap": {"type": "boolean", "description": "ASAP marker"},
                "size_text": {"type": ["string", "null"], "description": "Size"},
                "blocked": {"type": "boolean", "description": "Set to false to unblock"},
                "external_id": {"type": ["string", "null"], "description": "External ID"},
                "properties": {"type": "object", "description": "Custom properties as {id_N: value}"},
                "sprint_id": {"type": ["integer", "null"], "description": "Sprint ID (null to remove)"},
                "planned_start": {"type": ["string", "null"], "description": "Planned start date (ISO 8601)"},
                "planned_end": {"type": ["string", "null"], "description": "Planned end date (ISO 8601)"},
                "state": {"type": "integer", "enum": [1, 2, 3], "description": "Card state: 1=queued, 2=inProgress, 3=done"},
                "block_reason": {"type": ["string", "null"], "description": "Block reason text (null to clear)"},
                "locked": {"type": ["string", "null"], "description": "Lock identifier (null to unlock)"},
                "due_date_time_present": {"type": "boolean", "description": "True if due_date includes time component"},
                "expires_later": {"type": "boolean", "description": "Expires later flag"},
                "estimate_workload": {"type": "integer", "description": "Estimated workload in minutes (resource planning)"},
                "child_card_ids": {"type": "array", "items": {"type": "integer"}, "description": "Child card IDs to link"},
                "parent_card_ids": {"type": "array", "items": {"type": "integer"}, "description": "Parent card IDs to link"},
            },
            "required": ["card_id"],
        },
        operation=OperationSpec(
            method="PATCH",
            path_template="/cards/{card_id}",
            path_fields=("card_id",),
            body_fields=(
                "title",
                "description",
                "board_id",
                "column_id",
                "lane_id",
                "sort_order",
                "owner_id",
                "type_id",
                "condition",
                "due_date",
                "asap",
                "size_text",
                "blocked",
                "external_id",
                "properties",
                "sprint_id",
                "planned_start",
                "planned_end",
                "state",
                "block_reason",
                "locked",
                "due_date_time_present",
                "expires_later",
                "estimate_workload",
                "child_card_ids",
                "parent_card_ids",
            ),
        ),
        response_policy=ResponsePolicy(compact_supported=True, fields_supported=True, result_kind="entity"),
        examples=(
            ExampleSpec(command='kaiten cards update --card-id 123 --title "Renamed"', description="Update a card."),
            ExampleSpec(command='kaiten cards update --card-id 123 --title "Renamed" --compact --fields id,title,state --json', description="Update a card with a narrow response."),
        ),
    ),
    make_tool(
        canonical_name="cards.delete",
        mcp_alias="kaiten_delete_card",
        description="Soft-delete a Kaiten card (sets condition to deleted). Cards with time logs cannot be deleted.",
        input_schema={
            "type": "object",
            "properties": {
                "card_id": {"type": ["integer", "string"], "description": "Card ID or key"},
                "compact": {
                    "type": "boolean",
                    "description": "Return compact response without heavy fields (avatars, nested user objects)",
                    "default": False,
                },
                "fields": {
                    "type": "string",
                    "description": "Comma-separated field names to keep in the response. Example: 'id,title,state'",
                },
            },
            "required": ["card_id"],
        },
        operation=OperationSpec(method="DELETE", path_template="/cards/{card_id}", path_fields=("card_id",)),
        response_policy=ResponsePolicy(compact_supported=True, fields_supported=True, result_kind="entity"),
        examples=(
            ExampleSpec(command="kaiten cards delete --card-id 123", description="Delete a card."),
        ),
    ),
    make_tool(
        canonical_name="cards.archive",
        mcp_alias="kaiten_archive_card",
        description="Archive a Kaiten card (set condition to archived).",
        input_schema={
            "type": "object",
            "properties": {
                "card_id": {"type": ["integer", "string"], "description": "Card ID or key"},
                "compact": {
                    "type": "boolean",
                    "description": "Return compact response without heavy fields (avatars, nested user objects)",
                    "default": False,
                },
                "fields": {
                    "type": "string",
                    "description": "Comma-separated field names to keep in the response. Example: 'id,title,state'",
                },
            },
            "required": ["card_id"],
        },
        operation=OperationSpec(
            method="PATCH",
            path_template="/cards/{card_id}",
            path_fields=("card_id",),
            body_fields=("condition",),
        ),
        response_policy=ResponsePolicy(compact_supported=True, fields_supported=True, result_kind="entity"),
        runtime_behavior=RuntimeBehavior(request_shaper=archive_card_request),
        examples=(
            ExampleSpec(command="kaiten cards archive --card-id 123", description="Archive a card."),
        ),
    ),
    make_tool(
        canonical_name="cards.move",
        mcp_alias="kaiten_move_card",
        description="Move a Kaiten card to a different board, column, or lane.",
        input_schema={
            "type": "object",
            "properties": {
                "card_id": {"type": ["integer", "string"], "description": "Card ID or key"},
                "board_id": {"type": "integer", "description": "Target board ID"},
                "column_id": {"type": "integer", "description": "Target column ID"},
                "lane_id": {"type": "integer", "description": "Target lane ID"},
                "sort_order": {"type": "number", "description": "Position in cell"},
                "compact": {
                    "type": "boolean",
                    "description": "Return compact response without heavy fields (avatars, nested user objects)",
                    "default": False,
                },
                "fields": {
                    "type": "string",
                    "description": "Comma-separated field names to keep in the response. Example: 'id,title,state'",
                },
            },
            "required": ["card_id"],
        },
        operation=OperationSpec(
            method="PATCH",
            path_template="/cards/{card_id}",
            path_fields=("card_id",),
            body_fields=("board_id", "column_id", "lane_id", "sort_order"),
        ),
        response_policy=ResponsePolicy(compact_supported=True, fields_supported=True, result_kind="entity"),
        examples=(
            ExampleSpec(command="kaiten cards move --card-id 123 --column-id 10 --json", description="Move a card."),
        ),
    ),
    make_tool(
        canonical_name="cards.list-all",
        mcp_alias="kaiten_list_all_cards",
        description="Fetch all cards matching filters with automatic pagination.",
        input_schema={
            "type": "object",
            "properties": {
                **LIST_CARD_SCHEMA["properties"],
                "owner_ids": {"type": "string", "description": "Comma-separated owner IDs"},
                "responsible_ids": {"type": "string", "description": "Comma-separated responsible IDs"},
                "column_ids": {"type": "string", "description": "Comma-separated column IDs"},
                "type_ids": {"type": "string", "description": "Comma-separated type IDs"},
                "page_size": {"type": "integer", "description": "Cards per page (default 100, max 100)"},
                "max_pages": {"type": "integer", "description": "Safety limit on pages to fetch (default 50)"},
                "compact": {
                    "type": "boolean",
                    "description": "Return compact response without heavy fields (default true for bulk)",
                    "default": True,
                },
                "relations": {
                    "type": "string",
                    "description": "Relations to include or 'none' to exclude all nested objects (default 'none' for bulk).",
                    "default": "none",
                },
                "fields": {
                    "type": "string",
                    "description": "Comma-separated field names to return per card after pagination.",
                },
            },
        },
        operation=OperationSpec(method="GET", path_template="/cards"),
        response_policy=ResponsePolicy(compact_supported=True, fields_supported=True, result_kind="list", heavy=True),
        runtime_behavior=RuntimeBehavior(
            execution_mode="aggregated",
            custom_executor=execute_cards_list_all,
            compact_default=True,
        ),
        examples=(
            ExampleSpec(command="kaiten cards list-all --board-id 10 --page-size 20 --max-pages 2 --json", description="Fetch all matching cards with bounded pagination."),
        ),
    ),
)
