"""Service desk tool specs."""

from __future__ import annotations

from kaiten_cli.models import ExampleSpec, OperationSpec, ResponsePolicy, RuntimeBehavior
from kaiten_cli.registry.base import make_tool
from kaiten_cli.runtime_behaviors import archive_service_request, service_desk_stats_query_request
from kaiten_cli.transforms import DEFAULT_LIMIT


TOOLS = (
    make_tool(
        canonical_name="service-desk.requests.list",
        mcp_alias="kaiten_list_sd_requests",
        description="List Service Desk requests.",
        input_schema={"type": "object", "properties": {"query": {"type": "string", "description": "Search filter"}, "limit": {"type": "integer", "description": "Max results"}, "offset": {"type": "integer", "description": "Pagination offset"}}},
        operation=OperationSpec(method="GET", path_template="/service-desk/requests", query_fields=("query", "limit", "offset")),
        response_policy=ResponsePolicy(default_limit=DEFAULT_LIMIT, result_kind="list"),
        examples=(ExampleSpec(command="kaiten service-desk requests list --json", description="List Service Desk requests."),),
    ),
    make_tool(
        canonical_name="service-desk.requests.create",
        mcp_alias="kaiten_create_sd_request",
        description="Create a new Service Desk request.",
        input_schema={"type": "object", "properties": {"title": {"type": "string", "description": "Request title"}, "service_id": {"type": "integer", "description": "Service ID"}, "description": {"type": "string", "description": "Request description"}, "priority": {"type": "string", "description": "Request priority"}}, "required": ["title", "service_id"]},
        operation=OperationSpec(method="POST", path_template="/service-desk/requests", body_fields=("title", "service_id", "description", "priority")),
        examples=(ExampleSpec(command='kaiten service-desk requests create --title "Help" --service-id 1 --json', description="Create a request."),),
    ),
    make_tool(
        canonical_name="service-desk.requests.get",
        mcp_alias="kaiten_get_sd_request",
        description="Get a Service Desk request by ID.",
        input_schema={"type": "object", "properties": {"request_id": {"type": "integer", "description": "Request ID"}}, "required": ["request_id"]},
        operation=OperationSpec(method="GET", path_template="/service-desk/requests/{request_id}", path_fields=("request_id",)),
        examples=(ExampleSpec(command="kaiten service-desk requests get --request-id 1 --json", description="Get a request."),),
    ),
    make_tool(
        canonical_name="service-desk.requests.update",
        mcp_alias="kaiten_update_sd_request",
        description="Update a Service Desk request.",
        input_schema={"type": "object", "properties": {"request_id": {"type": "integer", "description": "Request ID"}, "title": {"type": "string", "description": "Request title"}, "description": {"type": "string", "description": "Request description"}, "priority": {"type": "string", "description": "Request priority"}}, "required": ["request_id"]},
        operation=OperationSpec(method="PATCH", path_template="/service-desk/requests/{request_id}", path_fields=("request_id",), body_fields=("title", "description", "priority")),
        examples=(ExampleSpec(command='kaiten service-desk requests update --request-id 1 --priority high --json', description="Update a request."),),
    ),
    make_tool(
        canonical_name="service-desk.requests.delete",
        mcp_alias="kaiten_delete_sd_request",
        description="Delete a Service Desk request.",
        input_schema={"type": "object", "properties": {"request_id": {"type": "integer", "description": "Request ID"}}, "required": ["request_id"]},
        operation=OperationSpec(method="DELETE", path_template="/service-desk/requests/{request_id}", path_fields=("request_id",)),
        examples=(ExampleSpec(command="kaiten service-desk requests delete --request-id 1 --json", description="Delete a request."),),
    ),
    make_tool(
        canonical_name="service-desk.services.list",
        mcp_alias="kaiten_list_sd_services",
        description="List Service Desk services.",
        input_schema={"type": "object", "properties": {"query": {"type": "string", "description": "Search filter"}, "include_archived": {"type": "boolean", "description": "Include archived services"}, "limit": {"type": "integer", "description": "Max results"}, "offset": {"type": "integer", "description": "Pagination offset"}}},
        operation=OperationSpec(method="GET", path_template="/service-desk/services", query_fields=("query", "include_archived", "limit", "offset")),
        response_policy=ResponsePolicy(default_limit=DEFAULT_LIMIT, result_kind="list"),
        examples=(ExampleSpec(command="kaiten service-desk services list --json", description="List services."),),
    ),
    make_tool(
        canonical_name="service-desk.services.get",
        mcp_alias="kaiten_get_sd_service",
        description="Get a Service Desk service by ID.",
        input_schema={"type": "object", "properties": {"service_id": {"type": "integer", "description": "Service ID"}}, "required": ["service_id"]},
        operation=OperationSpec(method="GET", path_template="/service-desk/services/{service_id}", path_fields=("service_id",)),
        examples=(ExampleSpec(command="kaiten service-desk services get --service-id 1 --json", description="Get a service."),),
    ),
    make_tool(
        canonical_name="service-desk.services.create",
        mcp_alias="kaiten_create_sd_service",
        description="Create a new Service Desk service.",
        input_schema={"type": "object", "properties": {"name": {"type": "string", "description": "Service name"}, "board_id": {"type": "integer", "description": "Board ID"}, "position": {"type": "integer", "description": "Sort position"}, "description": {"type": "string", "description": "Service description"}, "template_description": {"type": "string", "description": "Default description template"}, "lng": {"type": "string", "enum": ["en", "ru"], "description": "Language code"}, "display_status": {"type": "string", "enum": ["by_column", "by_state"], "description": "How status is displayed"}, "column_id": {"type": "integer", "description": "Default column ID"}, "lane_id": {"type": "integer", "description": "Default lane ID"}, "type_id": {"type": "integer", "description": "Card type ID"}, "email_settings": {"type": "integer", "description": "Email settings bitmask"}, "fields_settings": {"type": "object", "description": "Request form fields configuration"}, "settings": {"type": "object", "description": "Additional settings"}, "allow_to_add_external_recipients": {"type": "boolean", "description": "Allow external recipients"}, "hide_in_list": {"type": "boolean", "description": "Hide service in list"}, "is_default": {"type": "boolean", "description": "Set as default service"}}, "required": ["name", "board_id", "position", "lng"]},
        operation=OperationSpec(method="POST", path_template="/service-desk/services", body_fields=("name", "board_id", "position", "description", "template_description", "lng", "display_status", "column_id", "lane_id", "type_id", "email_settings", "fields_settings", "settings", "allow_to_add_external_recipients", "hide_in_list", "is_default")),
        examples=(ExampleSpec(command='kaiten service-desk services create --name Support --board-id 1 --position 1 --lng en --json', description="Create a service."),),
    ),
    make_tool(
        canonical_name="service-desk.services.update",
        mcp_alias="kaiten_update_sd_service",
        description="Update a Service Desk service.",
        input_schema={"type": "object", "properties": {"service_id": {"type": "integer", "description": "Service ID"}, "name": {"type": "string", "description": "Service name"}, "description": {"type": "string", "description": "Service description"}, "template_description": {"type": "string", "description": "Default description template"}, "lng": {"type": "string", "description": "Language code"}, "display_status": {"type": "string", "enum": ["by_column", "by_state"], "description": "How status is displayed"}, "board_id": {"type": "integer", "description": "Board ID"}, "column_id": {"type": "integer", "description": "Default column ID"}, "lane_id": {"type": "integer", "description": "Default lane ID"}, "type_id": {"type": "integer", "description": "Card type ID"}, "position": {"type": "integer", "description": "Sort position"}, "email_settings": {"type": "integer", "description": "Email settings bitmask"}, "fields_settings": {"type": "object", "description": "Request form fields configuration"}, "settings": {"type": "object", "description": "Additional settings"}, "archived": {"type": "boolean", "description": "Archive or unarchive service"}, "allow_to_add_external_recipients": {"type": "boolean", "description": "Allow external recipients"}, "hide_in_list": {"type": "boolean", "description": "Hide service in list"}}, "required": ["service_id"]},
        operation=OperationSpec(method="PATCH", path_template="/service-desk/services/{service_id}", path_fields=("service_id",), body_fields=("name", "description", "template_description", "lng", "display_status", "board_id", "column_id", "lane_id", "type_id", "position", "email_settings", "fields_settings", "settings", "archived", "allow_to_add_external_recipients", "hide_in_list")),
        examples=(ExampleSpec(command='kaiten service-desk services update --service-id 1 --archived --json', description="Update a service."),),
    ),
    make_tool(
        canonical_name="service-desk.services.delete",
        mcp_alias="kaiten_delete_sd_service",
        description="Archive a Service Desk service.",
        input_schema={"type": "object", "properties": {"service_id": {"type": "integer", "description": "Service ID"}}, "required": ["service_id"]},
        operation=OperationSpec(method="PATCH", path_template="/service-desk/services/{service_id}", path_fields=("service_id",)),
        runtime_behavior=RuntimeBehavior(request_shaper=archive_service_request),
        examples=(ExampleSpec(command="kaiten service-desk services delete --service-id 1 --json", description="Archive a service."),),
    ),
    make_tool(
        canonical_name="service-desk.organizations.list",
        mcp_alias="kaiten_list_sd_organizations",
        description="List Service Desk organizations.",
        input_schema={"type": "object", "properties": {"query": {"type": "string", "description": "Search filter"}, "includeUsers": {"type": "boolean", "description": "Include organization users"}, "limit": {"type": "integer", "description": "Max results"}, "offset": {"type": "integer", "description": "Pagination offset"}}},
        operation=OperationSpec(method="GET", path_template="/service-desk/organizations", query_fields=("query", "includeUsers", "limit", "offset")),
        response_policy=ResponsePolicy(default_limit=DEFAULT_LIMIT, result_kind="list"),
        examples=(ExampleSpec(command="kaiten service-desk organizations list --json", description="List organizations."),),
    ),
    make_tool(
        canonical_name="service-desk.organizations.create",
        mcp_alias="kaiten_create_sd_organization",
        description="Create a Service Desk organization.",
        input_schema={"type": "object", "properties": {"name": {"type": "string", "description": "Organization name"}, "description": {"type": "string", "description": "Organization description"}}, "required": ["name"]},
        operation=OperationSpec(method="POST", path_template="/service-desk/organizations", body_fields=("name", "description")),
        examples=(ExampleSpec(command='kaiten service-desk organizations create --name Org --json', description="Create an organization."),),
    ),
    make_tool(
        canonical_name="service-desk.organizations.get",
        mcp_alias="kaiten_get_sd_organization",
        description="Get a Service Desk organization by ID.",
        input_schema={"type": "object", "properties": {"organization_id": {"type": "integer", "description": "Organization ID"}}, "required": ["organization_id"]},
        operation=OperationSpec(method="GET", path_template="/service-desk/organizations/{organization_id}", path_fields=("organization_id",)),
        examples=(ExampleSpec(command="kaiten service-desk organizations get --organization-id 1 --json", description="Get an organization."),),
    ),
    make_tool(
        canonical_name="service-desk.organizations.update",
        mcp_alias="kaiten_update_sd_organization",
        description="Update a Service Desk organization.",
        input_schema={"type": "object", "properties": {"organization_id": {"type": "integer", "description": "Organization ID"}, "name": {"type": "string", "description": "Organization name"}, "description": {"type": "string", "description": "Organization description"}}, "required": ["organization_id"]},
        operation=OperationSpec(method="PATCH", path_template="/service-desk/organizations/{organization_id}", path_fields=("organization_id",), body_fields=("name", "description")),
        examples=(ExampleSpec(command='kaiten service-desk organizations update --organization-id 1 --name Org2 --json', description="Update an organization."),),
    ),
    make_tool(
        canonical_name="service-desk.organizations.delete",
        mcp_alias="kaiten_delete_sd_organization",
        description="Delete a Service Desk organization.",
        input_schema={"type": "object", "properties": {"organization_id": {"type": "integer", "description": "Organization ID"}}, "required": ["organization_id"]},
        operation=OperationSpec(method="DELETE", path_template="/service-desk/organizations/{organization_id}", path_fields=("organization_id",)),
        examples=(ExampleSpec(command="kaiten service-desk organizations delete --organization-id 1 --json", description="Delete an organization."),),
    ),
    make_tool(
        canonical_name="service-desk.sla.list",
        mcp_alias="kaiten_list_sd_sla",
        description="List Service Desk SLA policies.",
        input_schema={"type": "object", "properties": {"limit": {"type": "integer", "description": "Max results"}, "offset": {"type": "integer", "description": "Pagination offset"}}},
        operation=OperationSpec(method="GET", path_template="/service-desk/sla", query_fields=("limit", "offset")),
        response_policy=ResponsePolicy(default_limit=DEFAULT_LIMIT, result_kind="list"),
        examples=(ExampleSpec(command="kaiten service-desk sla list --json", description="List SLA policies."),),
    ),
    make_tool(
        canonical_name="service-desk.sla.get",
        mcp_alias="kaiten_get_sd_sla",
        description="Get a Service Desk SLA policy by ID.",
        input_schema={"type": "object", "properties": {"sla_id": {"type": "string", "description": "SLA ID (UUID)"}}, "required": ["sla_id"]},
        operation=OperationSpec(method="GET", path_template="/service-desk/sla/{sla_id}", path_fields=("sla_id",)),
        examples=(ExampleSpec(command="kaiten service-desk sla get --sla-id sla-1 --json", description="Get an SLA policy."),),
    ),
    make_tool(
        canonical_name="service-desk.sla.create",
        mcp_alias="kaiten_create_sd_sla",
        description="Create a Service Desk SLA policy.",
        input_schema={"type": "object", "properties": {"name": {"type": "string", "description": "SLA policy name"}, "rules": {"type": "array", "items": {"type": "object"}, "description": "SLA rules"}, "notification_settings": {"type": "object", "description": "Notification configuration"}, "v2": {"type": "boolean", "description": "Use v2 SLA format"}}, "required": ["name", "rules"]},
        operation=OperationSpec(method="POST", path_template="/service-desk/sla", body_fields=("name", "rules", "notification_settings", "v2")),
        examples=(ExampleSpec(command='kaiten service-desk sla create --name SLA --rules \'[]\' --json', description="Create an SLA policy."),),
    ),
    make_tool(
        canonical_name="service-desk.sla.update",
        mcp_alias="kaiten_update_sd_sla",
        description="Update a Service Desk SLA policy.",
        input_schema={"type": "object", "properties": {"sla_id": {"type": "string", "description": "SLA ID (UUID)"}, "name": {"type": "string", "description": "SLA policy name"}, "status": {"type": "string", "description": "SLA status"}, "notification_settings": {"type": "object", "description": "Notification configuration"}, "should_delete_sla_from_cards": {"type": "boolean", "description": "Remove SLA from cards when deactivating"}}, "required": ["sla_id"]},
        operation=OperationSpec(method="PATCH", path_template="/service-desk/sla/{sla_id}", path_fields=("sla_id",), body_fields=("name", "status", "notification_settings", "should_delete_sla_from_cards")),
        examples=(ExampleSpec(command='kaiten service-desk sla update --sla-id sla-1 --status inactive --json', description="Update an SLA policy."),),
    ),
    make_tool(
        canonical_name="service-desk.sla.delete",
        mcp_alias="kaiten_delete_sd_sla",
        description="Delete a Service Desk SLA policy.",
        input_schema={"type": "object", "properties": {"sla_id": {"type": "string", "description": "SLA ID (UUID)"}}, "required": ["sla_id"]},
        operation=OperationSpec(method="DELETE", path_template="/service-desk/sla/{sla_id}", path_fields=("sla_id",)),
        examples=(ExampleSpec(command="kaiten service-desk sla delete --sla-id sla-1 --json", description="Delete an SLA policy."),),
    ),
    make_tool(
        canonical_name="service-desk.template-answers.list",
        mcp_alias="kaiten_list_sd_template_answers",
        description="List Service Desk template answers.",
        input_schema={"type": "object", "properties": {}},
        operation=OperationSpec(method="GET", path_template="/service-desk/template-answers"),
        examples=(ExampleSpec(command="kaiten service-desk template-answers list --json", description="List template answers."),),
    ),
    make_tool(
        canonical_name="service-desk.template-answers.get",
        mcp_alias="kaiten_get_sd_template_answer",
        description="Get a Service Desk template answer by ID.",
        input_schema={"type": "object", "properties": {"template_answer_id": {"type": "string", "description": "Template answer ID (UUID)"}}, "required": ["template_answer_id"]},
        operation=OperationSpec(method="GET", path_template="/service-desk/template-answers/{template_answer_id}", path_fields=("template_answer_id",)),
        examples=(ExampleSpec(command="kaiten service-desk template-answers get --template-answer-id ta-1 --json", description="Get a template answer."),),
    ),
    make_tool(
        canonical_name="service-desk.template-answers.create",
        mcp_alias="kaiten_create_sd_template_answer",
        description="Create a Service Desk template answer.",
        input_schema={"type": "object", "properties": {"name": {"type": "string", "description": "Template name"}, "text": {"type": "string", "description": "Template answer text"}}, "required": ["name", "text"]},
        operation=OperationSpec(method="POST", path_template="/service-desk/template-answers", body_fields=("name", "text")),
        examples=(ExampleSpec(command='kaiten service-desk template-answers create --name Hello --text "Hi" --json', description="Create a template answer."),),
    ),
    make_tool(
        canonical_name="service-desk.template-answers.update",
        mcp_alias="kaiten_update_sd_template_answer",
        description="Update a Service Desk template answer.",
        input_schema={"type": "object", "properties": {"template_answer_id": {"type": "string", "description": "Template answer ID (UUID)"}, "name": {"type": "string", "description": "Template name"}, "text": {"type": "string", "description": "Template answer text"}}, "required": ["template_answer_id"]},
        operation=OperationSpec(method="PATCH", path_template="/service-desk/template-answers/{template_answer_id}", path_fields=("template_answer_id",), body_fields=("name", "text")),
        examples=(ExampleSpec(command='kaiten service-desk template-answers update --template-answer-id ta-1 --text "Hello" --json', description="Update a template answer."),),
    ),
    make_tool(
        canonical_name="service-desk.template-answers.delete",
        mcp_alias="kaiten_delete_sd_template_answer",
        description="Delete a Service Desk template answer.",
        input_schema={"type": "object", "properties": {"template_answer_id": {"type": "string", "description": "Template answer ID (UUID)"}}, "required": ["template_answer_id"]},
        operation=OperationSpec(method="DELETE", path_template="/service-desk/template-answers/{template_answer_id}", path_fields=("template_answer_id",)),
        examples=(ExampleSpec(command="kaiten service-desk template-answers delete --template-answer-id ta-1 --json", description="Delete a template answer."),),
    ),
    make_tool(
        canonical_name="service-desk.sla-rules.create",
        mcp_alias="kaiten_create_sla_rule",
        description="Create a rule within an SLA policy.",
        input_schema={"type": "object", "properties": {"sla_id": {"type": "string", "description": "SLA ID (UUID)"}, "type": {"type": "string", "description": "Rule type"}, "calendar_id": {"type": "string", "description": "Calendar ID"}, "start_column_uid": {"type": "string", "description": "Start column UID"}, "finish_column_uid": {"type": "string", "description": "Finish column UID"}, "estimated_time": {"type": "integer", "description": "Target time in seconds"}, "notification_settings": {"type": "object", "description": "Notification configuration"}}, "required": ["sla_id"]},
        operation=OperationSpec(method="POST", path_template="/service-desk/sla/{sla_id}/rules", path_fields=("sla_id",), body_fields=("type", "calendar_id", "start_column_uid", "finish_column_uid", "estimated_time", "notification_settings")),
        examples=(ExampleSpec(command='kaiten service-desk sla-rules create --sla-id sla-1 --type response --json', description="Create an SLA rule."),),
    ),
    make_tool(
        canonical_name="service-desk.sla-rules.update",
        mcp_alias="kaiten_update_sla_rule",
        description="Update a rule within an SLA policy.",
        input_schema={"type": "object", "properties": {"sla_id": {"type": "string", "description": "SLA ID (UUID)"}, "rule_id": {"type": "string", "description": "Rule ID"}, "type": {"type": "string", "description": "Rule type"}, "calendar_id": {"type": "string", "description": "Calendar ID"}, "start_column_uid": {"type": "string", "description": "Start column UID"}, "finish_column_uid": {"type": "string", "description": "Finish column UID"}, "estimated_time": {"type": "integer", "description": "Target time in seconds"}, "notification_settings": {"type": "object", "description": "Notification configuration"}}, "required": ["sla_id", "rule_id"]},
        operation=OperationSpec(method="PATCH", path_template="/service-desk/sla/{sla_id}/rules/{rule_id}", path_fields=("sla_id", "rule_id"), body_fields=("type", "calendar_id", "start_column_uid", "finish_column_uid", "estimated_time", "notification_settings")),
        examples=(ExampleSpec(command='kaiten service-desk sla-rules update --sla-id sla-1 --rule-id rule-1 --estimated-time 60 --json', description="Update an SLA rule."),),
    ),
    make_tool(
        canonical_name="service-desk.sla-rules.delete",
        mcp_alias="kaiten_delete_sla_rule",
        description="Delete a rule from an SLA policy.",
        input_schema={"type": "object", "properties": {"sla_id": {"type": "string", "description": "SLA ID (UUID)"}, "rule_id": {"type": "string", "description": "Rule ID"}}, "required": ["sla_id", "rule_id"]},
        operation=OperationSpec(method="DELETE", path_template="/service-desk/sla/{sla_id}/rules/{rule_id}", path_fields=("sla_id", "rule_id")),
        examples=(ExampleSpec(command="kaiten service-desk sla-rules delete --sla-id sla-1 --rule-id rule-1 --json", description="Delete an SLA rule."),),
    ),
    make_tool(
        canonical_name="service-desk.sla.recalculate",
        mcp_alias="kaiten_recalculate_sla",
        description="Trigger recalculation of SLA measurements.",
        input_schema={"type": "object", "properties": {"sla_id": {"type": "string", "description": "SLA ID (UUID)"}}, "required": ["sla_id"]},
        operation=OperationSpec(method="POST", path_template="/service-desk/sla/{sla_id}/recalculate-measurements", path_fields=("sla_id",)),
        examples=(ExampleSpec(command="kaiten service-desk sla recalculate --sla-id sla-1 --json", description="Recalculate SLA measurements."),),
    ),
    make_tool(
        canonical_name="service-desk.users.list",
        mcp_alias="kaiten_list_sd_users",
        description="List Service Desk users.",
        input_schema={"type": "object", "properties": {"query": {"type": "string", "description": "Search filter"}, "limit": {"type": "integer", "description": "Max results"}, "offset": {"type": "integer", "description": "Pagination offset"}, "include_paid_users": {"type": "boolean", "description": "Include paid users"}, "include_all_sd_users": {"type": "boolean", "description": "Include all SD users"}}},
        operation=OperationSpec(method="GET", path_template="/service-desk/users", query_fields=("query", "limit", "offset", "include_paid_users", "include_all_sd_users")),
        response_policy=ResponsePolicy(default_limit=DEFAULT_LIMIT, result_kind="list"),
        examples=(ExampleSpec(command="kaiten service-desk users list --json", description="List Service Desk users."),),
    ),
    make_tool(
        canonical_name="service-desk.users.update",
        mcp_alias="kaiten_update_sd_user",
        description="Update a Service Desk user profile.",
        input_schema={"type": "object", "properties": {"user_id": {"type": "integer", "description": "User ID"}, "full_name": {"type": "string", "description": "User full name"}, "lng": {"type": "string", "description": "Language code"}}, "required": ["user_id"]},
        operation=OperationSpec(method="PATCH", path_template="/service-desk/users/{user_id}", path_fields=("user_id",), body_fields=("full_name", "lng")),
        examples=(ExampleSpec(command='kaiten service-desk users update --user-id 1 --full-name "Alice" --json', description="Update a Service Desk user."),),
    ),
    make_tool(
        canonical_name="service-desk.users.set-temp-password",
        mcp_alias="kaiten_set_sd_user_temp_password",
        description="Generate a temporary password for a Service Desk user.",
        input_schema={"type": "object", "properties": {"user_id": {"type": "integer", "description": "User ID"}}, "required": ["user_id"]},
        operation=OperationSpec(method="PATCH", path_template="/service-desk/users/set-temporary-password/{user_id}", path_fields=("user_id",)),
        examples=(ExampleSpec(command="kaiten service-desk users set-temp-password --user-id 1 --json", description="Generate a temporary password."),),
    ),
    make_tool(
        canonical_name="service-desk.organization-users.add",
        mcp_alias="kaiten_add_sd_org_user",
        description="Add a user to a Service Desk organization.",
        input_schema={"type": "object", "properties": {"organization_id": {"type": "integer", "description": "Organization ID"}, "user_id": {"type": "integer", "description": "User ID"}, "permissions": {"type": "integer", "description": "Permission bitmask"}}, "required": ["organization_id", "user_id"]},
        operation=OperationSpec(method="POST", path_template="/service-desk/organizations/{organization_id}/users", path_fields=("organization_id",), body_fields=("user_id", "permissions")),
        examples=(ExampleSpec(command="kaiten service-desk organization-users add --organization-id 1 --user-id 2 --json", description="Add an organization user."),),
    ),
    make_tool(
        canonical_name="service-desk.organization-users.update",
        mcp_alias="kaiten_update_sd_org_user",
        description="Update a user's permissions in a Service Desk organization.",
        input_schema={"type": "object", "properties": {"organization_id": {"type": "integer", "description": "Organization ID"}, "user_id": {"type": "integer", "description": "User ID"}, "permissions": {"type": "integer", "description": "Permission bitmask"}}, "required": ["organization_id", "user_id"]},
        operation=OperationSpec(method="PATCH", path_template="/service-desk/organizations/{organization_id}/users/{user_id}", path_fields=("organization_id", "user_id"), body_fields=("permissions",)),
        examples=(ExampleSpec(command="kaiten service-desk organization-users update --organization-id 1 --user-id 2 --permissions 7 --json", description="Update organization-user permissions."),),
    ),
    make_tool(
        canonical_name="service-desk.organization-users.remove",
        mcp_alias="kaiten_remove_sd_org_user",
        description="Remove a user from a Service Desk organization.",
        input_schema={"type": "object", "properties": {"organization_id": {"type": "integer", "description": "Organization ID"}, "user_id": {"type": "integer", "description": "User ID"}}, "required": ["organization_id", "user_id"]},
        operation=OperationSpec(method="DELETE", path_template="/service-desk/organizations/{organization_id}/users/{user_id}", path_fields=("organization_id", "user_id")),
        examples=(ExampleSpec(command="kaiten service-desk organization-users remove --organization-id 1 --user-id 2 --json", description="Remove an organization user."),),
    ),
    make_tool(
        canonical_name="service-desk.organization-users.batch-add",
        mcp_alias="kaiten_batch_add_sd_org_users",
        description="Add multiple users to a Service Desk organization.",
        input_schema={"type": "object", "properties": {"organization_id": {"type": "integer", "description": "Organization ID"}, "user_ids": {"type": "array", "items": {"type": "integer"}, "description": "User IDs"}} , "required": ["organization_id", "user_ids"]},
        operation=OperationSpec(method="PATCH", path_template="/service-desk/organizations/{organization_id}/users", path_fields=("organization_id",), body_fields=("user_ids",)),
        examples=(ExampleSpec(command="kaiten service-desk organization-users batch-add --organization-id 1 --user-ids '[1,2]' --json", description="Batch-add organization users."),),
    ),
    make_tool(
        canonical_name="service-desk.organization-users.batch-remove",
        mcp_alias="kaiten_batch_remove_sd_org_users",
        description="Remove multiple users from a Service Desk organization.",
        input_schema={"type": "object", "properties": {"organization_id": {"type": "integer", "description": "Organization ID"}, "user_ids": {"type": "array", "items": {"type": "integer"}, "description": "User IDs"}} , "required": ["organization_id", "user_ids"]},
        operation=OperationSpec(method="DELETE", path_template="/service-desk/organizations/{organization_id}/users", path_fields=("organization_id",), body_fields=("user_ids",)),
        examples=(ExampleSpec(command="kaiten service-desk organization-users batch-remove --organization-id 1 --user-ids '[1,2]' --json", description="Batch-remove organization users."),),
    ),
    make_tool(
        canonical_name="service-desk.settings.get",
        mcp_alias="kaiten_get_sd_settings",
        description="Get current Service Desk settings.",
        input_schema={"type": "object", "properties": {}},
        operation=OperationSpec(method="GET", path_template="/sd-settings/current"),
        examples=(ExampleSpec(command="kaiten service-desk settings get --json", description="Get Service Desk settings."),),
    ),
    make_tool(
        canonical_name="service-desk.settings.update",
        mcp_alias="kaiten_update_sd_settings",
        description="Update Service Desk settings.",
        input_schema={"type": "object", "properties": {"service_desk_settings": {"type": "object", "description": "Service Desk configuration object"}}, "required": ["service_desk_settings"]},
        operation=OperationSpec(method="PATCH", path_template="/sd-settings/current", body_fields=("service_desk_settings",)),
        examples=(ExampleSpec(command="kaiten service-desk settings update --service-desk-settings '{}' --json", description="Update Service Desk settings."),),
    ),
    make_tool(
        canonical_name="service-desk.stats.get",
        mcp_alias="kaiten_get_sd_stats",
        description="Get Service Desk statistics.",
        input_schema={"type": "object", "properties": {"date_from": {"type": "string", "description": "Start date (ISO format)"}, "date_to": {"type": "string", "description": "End date (ISO format)"}, "service_id": {"type": "integer", "description": "Service ID"}, "report": {"type": "boolean", "description": "Enable report mode"}}},
        operation=OperationSpec(method="GET", path_template="/service-desk/stats", query_fields=("date_from", "date_to", "service_id", "report")),
        runtime_behavior=RuntimeBehavior(request_shaper=service_desk_stats_query_request),
        examples=(ExampleSpec(command="kaiten service-desk stats get --date-from 2026-01-01 --json", description="Get Service Desk statistics."),),
    ),
    make_tool(
        canonical_name="service-desk.sla.stats",
        mcp_alias="kaiten_get_sd_sla_stats",
        description="Get Service Desk SLA statistics.",
        input_schema={"type": "object", "properties": {"date_from": {"type": "string", "description": "Start date (ISO format)"}, "date_to": {"type": "string", "description": "End date (ISO format)"}, "sla_id": {"type": "string", "description": "SLA ID"}, "service_id": {"type": "integer", "description": "Service ID"}, "responsible_id": {"type": "integer", "description": "Responsible user ID"}, "card_type_ids": {"type": "string", "description": "JSON array of card type IDs"}, "tag_ids": {"type": "string", "description": "JSON array of tag IDs"}}},
        operation=OperationSpec(method="GET", path_template="/service-desk/sla-stats", query_fields=("date_from", "date_to", "sla_id", "service_id", "responsible_id", "card_type_ids", "tag_ids")),
        response_policy=ResponsePolicy(heavy=True),
        examples=(ExampleSpec(command="kaiten service-desk sla stats --sla-id sla-1 --json", description="Get Service Desk SLA statistics."),),
    ),
    make_tool(
        canonical_name="service-desk.vote-properties.add",
        mcp_alias="kaiten_add_service_vote_property",
        description="Add a custom property as a vote property for a Service Desk service.",
        input_schema={"type": "object", "properties": {"service_id": {"type": "integer", "description": "Service ID"}, "id": {"type": "integer", "description": "Custom property ID"}}, "required": ["service_id", "id"]},
        operation=OperationSpec(method="POST", path_template="/service-desk/services/{service_id}/vote-properties", path_fields=("service_id",), body_fields=("id",)),
        examples=(ExampleSpec(command="kaiten service-desk vote-properties add --service-id 1 --id 2 --json", description="Add a vote property."),),
    ),
    make_tool(
        canonical_name="service-desk.vote-properties.remove",
        mcp_alias="kaiten_remove_service_vote_property",
        description="Remove a vote property from a Service Desk service.",
        input_schema={"type": "object", "properties": {"service_id": {"type": "integer", "description": "Service ID"}, "property_id": {"type": "integer", "description": "Vote property ID"}}, "required": ["service_id", "property_id"]},
        operation=OperationSpec(method="DELETE", path_template="/service-desk/services/{service_id}/vote-properties/{property_id}", path_fields=("service_id", "property_id")),
        examples=(ExampleSpec(command="kaiten service-desk vote-properties remove --service-id 1 --property-id 2 --json", description="Remove a vote property."),),
    ),
    make_tool(
        canonical_name="card-slas.attach",
        mcp_alias="kaiten_attach_card_sla",
        description="Attach an SLA policy to a card.",
        input_schema={"type": "object", "properties": {"card_id": {"type": "integer", "description": "Card ID"}, "sla_id": {"type": "string", "description": "SLA ID (UUID)"}}, "required": ["card_id", "sla_id"]},
        operation=OperationSpec(method="POST", path_template="/cards/{card_id}/slas", path_fields=("card_id",), body_fields=("sla_id",)),
        examples=(ExampleSpec(command="kaiten card-slas attach --card-id 1 --sla-id sla-1 --json", description="Attach an SLA to a card."),),
    ),
    make_tool(
        canonical_name="card-slas.detach",
        mcp_alias="kaiten_detach_card_sla",
        description="Detach an SLA policy from a card.",
        input_schema={"type": "object", "properties": {"card_id": {"type": "integer", "description": "Card ID"}, "sla_id": {"type": "string", "description": "SLA ID (UUID)"}}, "required": ["card_id", "sla_id"]},
        operation=OperationSpec(method="DELETE", path_template="/cards/{card_id}/slas/{sla_id}", path_fields=("card_id", "sla_id")),
        examples=(ExampleSpec(command="kaiten card-slas detach --card-id 1 --sla-id sla-1 --json", description="Detach an SLA from a card."),),
    ),
    make_tool(
        canonical_name="card-sla-measurements.get",
        mcp_alias="kaiten_get_card_sla_measurements",
        description="Get SLA rule measurements for a card.",
        input_schema={"type": "object", "properties": {"card_id": {"type": "integer", "description": "Card ID"}}, "required": ["card_id"]},
        operation=OperationSpec(method="GET", path_template="/cards/{card_id}/sla-rules-measurements", path_fields=("card_id",)),
        examples=(ExampleSpec(command="kaiten card-sla-measurements get --card-id 1 --json", description="Get card SLA measurements."),),
    ),
    make_tool(
        canonical_name="space-sla-measurements.get",
        mcp_alias="kaiten_get_space_sla_measurements",
        description="Get SLA rule measurements for all cards in a space.",
        input_schema={"type": "object", "properties": {"space_id": {"type": "integer", "description": "Space ID"}}, "required": ["space_id"]},
        operation=OperationSpec(method="GET", path_template="/spaces/{space_id}/sla-rules-measurements", path_fields=("space_id",)),
        examples=(ExampleSpec(command="kaiten space-sla-measurements get --space-id 1 --json", description="Get space SLA measurements."),),
    ),
)
